# Generated by Django 2.0.4 on 2018-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingprompt',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
