# Generated by Django 2.0.4 on 2018-04-14 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vivian', '0002_writingprompt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingprompt',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
