# Generated by Django 2.0.4 on 2018-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivian', '0003_writingprompt_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingprompt',
            name='url',
            field=models.CharField(default='www.example.com', max_length=100),
            preserve_default=False,
        ),
    ]
